const express = require('express')
const path = require('path')
const app = express()
app.use(express.static(path.join(__dirname, 'public')))
app.get('/ping', (req, res) => res.end('pong'))
app.listen(process.env.PORT || 4200)
